/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_lib_Myjni */

#ifndef _Included_com_demo_lib_Myjni
#define _Included_com_demo_lib_Myjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_lib_Myjni
 * Method:    add
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_demo_lib_Myjni_add
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_demo_lib_Myjni
 * Method:    add2
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_demo_lib_Myjni_add2
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
